### ISSUE TITLE
Menu entry missing

### ISSUE THREAD

**Issue by onknows** [k08045kk/CopyTabTitleUrl#22]
Today on two computers I checked, the menu option is no longer present. I reinstalled the add-on but this didn't help.

Both running Ubuntu 18.04 with latest FireFox.

**Comment by k08045kk** [comment]
Thank you for raising the issue.

I confirmed the reproduction of the problem. It will be fixed in the next version (v2.0.4).

### Problem
The default settings are not used in the new installation environment.
It is not the default setting, but most of the functions are disabled.

Workaround: Reset the options from the options screen.
You can use "Restore default settings" to change to the expected default settings. There is no problem even if you do not use it.


問題提起してくれてありがとう。

問題の再現を確認しました。次回バージョン（v2.0.4）で修正します。

### 問題
新規インストール環境で初期設定が使用されていない。
初期設定ではなく、ほとんどの機能が無効になった設定となっている。

回避策：オプション画面からオプションを再設定する。
「Restore default settings」を使用すると、想定されている初期設定に変更することができます。使用しなくても問題はありません。
