### ISSUE TITLE
How to add the Current DATE before TITLE and URL?

### ISSUE THREAD

**Issue by sfd99** [k08045kk/CopyTabTitleUrl#28]
Easy, 
very useful Chrome addon.
Thank you!

**Q:**
how do I add the _Current DATE_
_before_ the copied TITLE and URL ?.

I tried 
in the "format" options field:

    ${yyyy}-${MM}-${dd})-[${title}](${url})

but my format syntax must be wrong.

The TITLE and URL are copied to clipboard  OK,
but the DATE does not appear...
only the date "special format $ characters" show up
like this, after pasting:
 ${yyyy}-${MM}-${dd})

_**Help!**_
sfd99
San Francisco
latest Chrome browser
Ubuntu LINUX 20.04

**Comment by k08045kk** [comment]
1. ${yyyy}-${MM}-${dd})-[How to add the Current DATE before TITLE and URL? ・ Issue #28 ・ k08045kk/CopyTabTitleUrl](https://github.com/k08045kk/CopyTabTitleUrl/issues/28)
2. 2020-12-25)-[How to add the Current DATE before TITLE and URL? ・ Issue #28 ・ k08045kk/CopyTabTitleUrl](https://github.com/k08045kk/CopyTabTitleUrl/issues/28)

The above result is the result of me trying the format in question on this page. The format doesn't seem to be wrong. You should be getting a result of 1. And you should be looking for a result of 2.

I consider the following two possibilities. "The extension version may be out of date" and "Extended mode may not be enabled". The date and time output function is a new function since v1.5.4. It will not work with extensions older than v1.5.4. Also, the date and time output function is not a standard function. Only works if extended mode is enabled. Please enable "Extended mode".

Currently, I can't think of any other possibilities than the above two. If it still doesn't work, something may be wrong. We would appreciate any additional information you can think of.

**Comment by sfd99** [comment]
_Ok!_ 
Working 100% fine now!. :+1: 
Using ext **version 2.0.4** (installed today from **Chrome Store**)
under Ubuntu Linux 20.04.

Thanks again for your quick answer.
Best to you!.
