### ISSUE TITLE
format1 ${text} does not use selection when called by keyboard shortcut

### ISSUE THREAD

**Issue by Hubbitus** [k08045kk/CopyTabTitleUrl#42]
Hello.
Thank you for the extension. It looks very interesting.

Meantime it looks like there bug present.

I've try configure that to copy page link with selection by a keyboard shortcut:
![image](https://user-images.githubusercontent.com/720349/136624659-e1482c39-2780-4776-9bd2-e15b93a04ee3.png)

But that work as expected from the selection context menu (mouse click), but when I invoke that by keyboard shortcut (`Alt + L` in my example) `${text}` always resolved into the page title, instead of selected text!

**Comment by k08045kk** [comment]
Specification.
`${text}` will only work as selection text from the selection context menu. If no other action or selection is available, it will act as a page title.
See https://github.com/k08045kk/CopyTabTitleUrl#basic

This is due to a limitation of the WebExtensionsAPI. It may be able to work around this issue with content scripts, but this extension does not use content scripts. (#17)

Thank you for pointing this out.
