### ISSUE TITLE
Markdown URLs should be copied without spaces

### ISSUE THREAD

**Issue by mikkovedru** [k08045kk/CopyTabTitleUrl#52]
Markdown URLs should be copied without spaces.

- The URL: `https://www.scribblemaps.com/maps/view/Operational Map Ukraine/nBT8ffpeGH`. This is also how it is displayed in Firefox. 
![image](https://user-images.githubusercontent.com/2521942/189205028-30fe5f20-a346-4cd6-a8ea-94225a1a485d.png)

- The way URL is copied by the extension in the markdown format: `[www.scribblemaps.com: Operational Map Ukraine : Scribble Maps](https://www.scribblemaps.com/maps/view/Operational Map Ukraine/nBT8ffpeGH)` (notice spaces on both side of the word "Map" in the URL) - this leads to problems in such software as Obsidian
- How the URL should be in order to work: `[www.scribblemaps.com: Operational Map Ukraine : Scribble Maps](https://www.scribblemaps.com/maps/view/Operational%20Map%20Ukraine/nBT8ffpeGH)`

So it works when spaces are substituted with `%20`.

**Comment by k08045kk** [comment]
Thank you for your suggestions.

First, let me conclude. It is a problem with your extension settings. Please disable the "Decode the URL" option.

We recognized that this case was caused by the fact that `{$url}` (or similar function) for markdown does not replace spaces with `%20` when outputting URLs.

This extension has a "Decode the URL" option. This is a function that decodes the URL and outputs it. It is mainly used to recover multibyte characters such as Japanese from percent encoding. Half-width spaces are encoded as "%20" in percent encoding. The browser outputs a percent-encoded URL, and this extension can optionally decode the URL.

URLs can be output without decoding by disabling the "Decode the URL" option. This is an "Extended mode" feature and is disabled by default.

That is all.

**Comment by mikkovedru** [comment]
Thank you for such a quick and comprehensive answer! And thank you for your extension - it is really useful!

The reason why I have the "Decode the URL" option enabled is that I often use Cyrillic websites. And it really helps to have the URL actually readable and comprehensible in my text.

But at the same time, the space ought to be written as `%20`.

Could you please make an option to Decode the URL, unless it comes to Markdown unsupported characters like space?

**Comment by k08045kk** [comment]
Would like to discuss adding the feature in #53. This issue is closed.

Initial research has shown that the results are not good. We already know that the problem does not stop at single-byte spaces. We also know that there is no clear answer to this problem.
