### ISSUE TITLE
[FR] if/else conditionals

### ISSUE THREAD

**Issue by bonnebulle** [k08045kk/CopyTabTitleUrl#58]
Hey thanks very helpfull tool in my search workflow
I dont find it in documentation here...
it should be great to add some content/action if exists
EX/ If text_selected => add it ! 
( if not, dont )
Any clue how I can do it ?
Thanks again

**Comment by k08045kk** [comment]
Hello

I'm not exactly sure what "EX/If text_selected" means.

Do you mean "selected text on the page"?
Selected text is available from `${text}`, `${selectedText}`, `${linkSelectionTitle}`, `${selectionLinkTitle}`.
https://github.com/k08045kk/CopyTabTitleUrl#basic

Do you mean "branch processing using if/else"?
This extension cannot currently be used. Please consider using "bookmarklet", "user script", and "external program".

Is it caused by "some element on the page"?
This extension does not currently use content scripts. Therefore, you cannot access any elements on the page. Consider using similar extensions.

If it differs from the above, please add a more specific explanation.

that's all.

**Comment by bonnebulle** [comment]
Sorry am not so clear...
I mean "branch processing using if/else"
EXemple : 
IF text is selected in my tab 
then, add selected text (+ other things like newline/stuffs..)
in my output (format)
IF not, dont

My problem is not to add or not selected text if exists
but adding other stuff if selected text exists !

I will find an other way, bookmarklets, ok
The extension doing a Very good work !
IF/Else is some more, not the essential
Thanks
