### ISSUE TITLE
Customize names for `format` and `format2`

### ISSUE THREAD

**Issue by brandonaut** [k08045kk/CopyTabTitleUrl#72]
I would like to be able to customize the names for the custom formats, so I can easily remember which is which. For instance, I might want to name them "Markdown" and "HTML", or something else entirely, if I've customized the formats.

**Comment by k08045kk** [comment]
Thanks for trying the extension. 

Try the following setting changes: 

1. Enable [Use Extended Mode]
   If you are using Android Firefox, please also enable [Use Extended Edit Mode].
2. Edit context menu title
3. Enable [Use context menu title]

Now you can rename items in context menu and browser action popup. 
If the issue is still not resolved, please provide more detailed information.

For more information on the options, please refer to the following link
https://github.com/k08045kk/CopyTabTitleUrl/wiki/Options

That is all.

**Comment by brandonaut** [comment]
Perfect! This meets my need exactly. Thanks for the quick response.
